name: icc_parser
description: A pure-dart library used to parse ICC profiles and create color transformations based on them
version: 0.2.0
repository: https://github.com/NicolaVerbeeck/dart_icc_parser
topics: [ icc, color, profile, colorprofile, cmyk ]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ">= 1.17.0 < 2.0.0"
  fixnum: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  convert: ^3.1.1
  extra_pedantic: ^4.0.0
  lints: ">=2.0.0 <7.0.0"
  mocktail: ^1.0.3
  test: ^1.21.0

funding:
  - https://buymeacoffee.com/nicolaverbn
  - https://ko-fi.com/nicolaverbeeck