name: icc_parser
description: A library used to parse ICC profiles
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  collection: ^1.17.2
  fixnum: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  extra_pedantic: ^4.0.0
  lints: ^2.0.0
  test: ^1.21.0
